#!/usr/bin/env bash
#  script that transfers a file from our client to a server
if [[ $# -le 3 ]]; then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi

#!/usr/bin/env bash
#!/usr/bin/env bash
#checking for command line arguments

if [ $#-lt 4]

then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
#assigning paramentals to variables

path_to_file=$1
ip=$2
username=$3
path_to_shh_key=$4

#disabbling strict host key checking

scp-o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:-/"


# checking if the transfer was successful

if [ $? -eq 0 ]
then
	echo "FILE WAS TRANSFERED SUCCESSFULLY"
else
fi
