#!/usr/bin/env bash

#commands to install nginx on web sever

sudo apt-get update

sudo apt-get install nginx

sudo ufw 'Nginx HTTP'

echo "Hello world!" | sudo tee /var/www/html/index.htm

sudo nginx -t

sudo service nginx reload
