#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is
# redirecting to another page.
sudo apt-get update
sudo apt-get install -y nginx
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    location / {
        index index.html index.nginx-debian.html;
        }
} " > /etc/nginx/sites-available/default
sudo service nginx restart
